<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="tarique-OptiPlex-3060" ignored="0" name="RetryMultipleFailedTestCase" tests="8" failures="2" timestamp="22 Nov 2020 17:28:56 GMT" time="0.034" errors="0">
  <testcase name="testLogic" time="0.007" classname="com.practise.TestNGRetryLogics">
    <skipped/>
  </testcase> <!-- testLogic -->
  <testcase name="testLogic" time="0.001" classname="com.practise.TestNGRetryLogics">
    <skipped/>
  </testcase> <!-- testLogic -->
  <testcase name="testLogic" time="0.001" classname="com.practise.TestNGRetryLogics">
    <skipped/>
  </testcase> <!-- testLogic -->
  <testcase name="testLogic" time="0.001" classname="com.practise.TestNGRetryLogics">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.practise.TestNGRetryLogics.testLogic(TestNGRetryLogics.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testLogic -->
  <testcase name="testLogic1" time="0.001" classname="com.practise.TestNGRetryLogics">
    <skipped/>
  </testcase> <!-- testLogic1 -->
  <testcase name="testLogic1" time="0.001" classname="com.practise.TestNGRetryLogics">
    <skipped/>
  </testcase> <!-- testLogic1 -->
  <testcase name="testLogic1" time="0.0" classname="com.practise.TestNGRetryLogics">
    <skipped/>
  </testcase> <!-- testLogic1 -->
  <testcase name="testLogic1" time="0.001" classname="com.practise.TestNGRetryLogics">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.practise.TestNGRetryLogics.testLogic1(TestNGRetryLogics.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testLogic1 -->
</testsuite> <!-- RetryMultipleFailedTestCase -->
